"""foreign keys agains

Revision ID: 5913dff2f535
Revises: b9d61e1724a0
Create Date: 2018-10-27 14:05:56.567191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5913dff2f535'
down_revision = 'b9d61e1724a0'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('showrun', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form_data', 'show_run', ['showrun'], ['id'])
    op.add_column('sentence', sa.Column('showrun', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentence', 'show_run', ['showrun'], ['id'])
    op.add_column('sentence__shelly', sa.Column('showrun', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentence__shelly', 'show_run', ['showrun'], ['id'])
    op.add_column('state', sa.Column('showrun', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'state', 'show_run', ['showrun'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_column('state', 'showrun')
    op.drop_constraint(None, 'sentence__shelly', type_='foreignkey')
    op.drop_column('sentence__shelly', 'showrun')
    op.drop_constraint(None, 'sentence', type_='foreignkey')
    op.drop_column('sentence', 'showrun')
    op.drop_constraint(None, 'form_data', type_='foreignkey')
    op.drop_column('form_data', 'showrun')
    # ### end Alembic commands ###
