"""initial showrun

Revision ID: b9d61e1724a0
Revises: 122718621720
Create Date: 2018-10-27 12:58:10.657313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d61e1724a0'
down_revision = '122718621720'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('preshow', 'in_progress', 'complete', name='statusenum'), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_run')
    # ### end Alembic commands ###
